---
title: "Spin data simulation"
author: "Manuel Bohn"
output: html_document
---

```{r, message=F, warning=F}
library(tidyverse)
library(purrr)
library(copula)
library(langcog)
library(ggthemes)
```

# Data simulation for one item

## Item specs

*Average ME effect across age = 0.6

*Correlation between age and ME effect = 0.3

## Simulation specs

*100 simualtions for each age bin

```{r}
fun <- function (n){
  tmp <- normalCopula(
    0.3, # correlation btw. age and ME effect
    dim=2 )
  x <- rCopula(n, tmp)
  correct = qbinom(
    x[,1], 
    1, 
    .6) # average ME effect
  age= x[,2]
  
  data.frame(age = age,
             correct = correct)
    
}

n_sim <- 100

sim_60 <- map(seq_len(n_sim), ~fun(60))%>%
  map_df(bind_rows)%>%
  mutate(case = rep(1:60,length(seq_len(n_sim))),
         iter = rep(1:length(seq_len(n_sim)), each = 60),
         age_bin=cut(age, breaks=c(0, 1/3, 2/3, 1), labels=c("2","3","4")),
         sample = "n = 20 / age bin")

sim_90 <- map(seq_len(n_sim), ~fun(90))%>%
  map_df(bind_rows)%>%
  mutate(case = rep(1:90,length(seq_len(n_sim))),
         iter = rep(1:length(seq_len(n_sim)), each = 90),
         age_bin=cut(age, breaks=c(0, 1/3, 2/3, 1), labels=c("2","3","4")),
         sample = "n = 30 / age bin")

sim_120 <- map(seq_len(n_sim), ~fun(120))%>%
  map_df(bind_rows)%>%
  mutate(case = rep(1:120,length(seq_len(n_sim))),
         iter = rep(1:length(seq_len(n_sim)), each = 120),
         age_bin=cut(age, breaks=c(0, 1/3, 2/3, 1), labels=c("2","3","4")),
         sample = "n = 40 / age bin")

sim <- bind_rows(sim_60,sim_90,sim_120)
```

## Plotting the 100 simulations with age continuous

```{r plot, fig.width=10, fig.height=5}

ggplot(data = sim, aes(x = age, y = correct, group = iter, col = sample)) +
  geom_smooth(method = "glm", se = T, size = 0.25, alpha = .04)+
  geom_hline(yintercept = 0.5, lty=2)+
  facet_grid(~sample)+
  ylab("ME effect")+
  ylim(0,1)+
  theme_few()

```

## Plotting the 100 simulations by age bin

Each point is the mean from one simulation (with 95%CI). No vertical jitter.

```{r}
sim_bin <- sim %>%
  group_by(sample, iter, age_bin)%>%
  multi_boot_standard(col = "correct")

ggplot(sim_bin, aes(x = age_bin, y = mean, col = age_bin)) +
  geom_pointrange( aes(ymin = ci_lower, ymax = ci_upper),size = .3, alpha = .2, position = position_jitter(width = 0.35,height = 0))+
  geom_hline(yintercept = 0.5, lty=2)+
  facet_grid(~sample)+
  ylab("ME effect")+
  ylim(0,1)+
  theme_few() 
```


