---
title: "Kids Basic Mutual Exclusivity"
author: "Manuel Bohn"
output: html_document
---

```{r setup}
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(jsonlite)
library(readxl)
library(brms)
library(here)
#library(brmstools)
library(ggpubr)
library(rwebppl)
```

Importing and processing raw data locally (see next chunk for loading processed data)

```{r import data, include = F}
## importing data locally

files <- dir("~/Work/Spin/raw_data/kids/basic_me/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/Spin/raw_data/kids/basic_me/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  date <- str_sub(jf,44,str_length(jf)-11)
  id <- as_data_frame(jd$data$data) %>% mutate(test_date = date)
  raw_data <- bind_rows(raw_data, id)
}


length(unique(raw_data$subid))

d_raw <-raw_data %>%
  mutate(subid = ifelse(subid == "190314_3", "190314_3_me",subid),
         subid = ifelse(subid == "190221_6_me", "190321_6_me",subid),
         subid = ifelse(subid == "192203_4_me", "190322_4_me",subid),
         subage = ifelse(subid == "190313_5_me", "3",subage),
         test_date = as.Date(test_date))


log <- read_excel("../../SPIN-subject_log.xlsx", 1)%>%
  filter(Condition == "me")%>%
  mutate(dob = as.character(dob),
         dob = ifelse(subid == "190313_7_me", "2015-11-15",dob),
         dob = ifelse(subid == "190313_11_me", "2016-04-18",dob),
         dob = ifelse(subid == "190320_8_me", "2014-04-28",dob),
         dob = as.Date(dob))%>%
  select(subid,experimenter,keep_drop,sex,dob)


d_raw%>%
  group_by(subid)%>%
  summarise(n())%>%
  filter(!(subid %in% unique(log$subid)))


d <- left_join(d_raw,log, by = "subid")%>%
  filter(keep_drop == "keep")%>%
  mutate(age_num = lubridate::time_length(difftime(test_date,dob), "years"),
         age_num_month = lubridate::time_length(difftime(test_date,dob), "month"),
         age_num_month = round(age_num_month)/12,
         age_month = age_num_month - min(age_num_month),
         check_age = ifelse(substr(age_num,1,1) == subage, T, F))%>%
  filter(trial != "train1",
           trial != "train2")%>%
  mutate(item = familiar,
         age = age_num - min(age_num))%>%
  select(-pick_src, -test_date, -experimenter, - keep_drop, -dob, -sex, -check_age, - condition, -familiar, -rt)

write_csv(d, "../data/me.csv")
write_json(d, "../data/me.json")

d <- read_csv("../data/me.csv")%>%
  mutate(subage = factor(subage))
```

```{r}
# import data
d <- read_csv("../data/me.csv")%>%
  mutate(subage = factor(subage))

aoa_ratings_all <- read_xlsx(path = "../data/words_aoa_ratings.xlsx", sheet = 1)

aoa_ratings <- aoa_ratings_all %>%
  filter(Word %in% d$item )%>%
  mutate(mean_aoa = as.numeric(Rating.Mean),
         item = Word)%>%
  select(item,mean_aoa)
```


# Sample size per age bin

```{r kids per age group,echo = F }

d %>%
  group_by(subage)%>%
  summarise(n = length(unique(subid)))%>%
  knitr::kable(digits = 2)

```

# Plot filler by age

```{r filler by age, echo= FALSE, warning= FALSE}
pf1 <- d %>%
      filter(trial == "train1" | trial == "train2")%>%
  group_by(subage, subid) %>%
  summarise(correct = mean(correct)) 

pf2 <- pf1 %>%
  multi_boot_standard(col = "correct")


ggplot() +
  geom_jitter(data = pf1, aes(x = subage, y = correct, col = subage, alpha = .2),width = .3,height = .025)+
  geom_pointrange(data = pf2, aes(x = subage, y = mean, col = subage, ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_hline(yintercept = 0.5, lty=2)+
  labs(x="",y="Proportion Expected Choice")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+ 
  theme(axis.text.x=element_blank(),axis.ticks.x=element_blank())+
  scale_colour_solarized()
```

# Itmes by age bin

```{r plot by age, echo= FALSE}
p1 <- d %>%
  filter(trial != "train1",
         trial != "train2")%>%
  group_by(subage, familiar) %>%
  multi_boot_standard(col = "correct")%>%
  left_join(aoa_ratings)%>%
  ungroup()%>%
  mutate(familiar = fct_reorder(factor(familiar), mean_aoa))


ggplot(data = p1, aes(x = familiar, y = mean, group=1, col = subage)) +
  geom_hline(yintercept = 0.5, lty=2)+
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper),size = .8)+
  stat_summary(aes(group = subage, col = subage),fun.y=mean, geom="line")+
  labs(x="",y="Proportion Correct")+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  scale_colour_solarized()
```

# Plot with age as continuous variable

## Facets by item

```{r plot by numerical age, echo = F}
p2 <- d %>%
  filter(trial != "train1",
         trial != "train2")%>%
    left_join(aoa_ratings)%>%
  ungroup()%>%
  mutate(familiar = fct_reorder(factor(familiar), mean_aoa))

ggplot(data = p2, aes(x = age_num, y = correct, col = familiar, fill = familiar)) +
  geom_hline(yintercept = 0.5, lty=2)+
  geom_jitter(width = 0, height = 0.05, alpha = .6)+
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se = F, alpha = .5)+
  #geom_smooth(method = "loess", se = F, alpha = .5)+
  labs(x="Age",y="Mutual Exclusivity effect")+
  #facet_grid(~familiar)+
  #ggtitle("Data")+
  theme_few() +
  ylim(-0.05,1.05)+
  xlim(2,5)+
  guides(alpha = F)+ 
  scale_colour_viridis_d(name = "familiar object")+
  scale_fill_viridis_d(name = "familiar object")

ggsave("../graphs/me_by_item.png", width = 5, height = 4, scale = 1.2)
```

```{r plot by numerical age, echo = F}
p2 <- d %>%
  filter(trial != "train1",
         trial != "train2")%>%
    left_join(aoa_ratings)%>%
  ungroup()%>%
  mutate(familiar = fct_reorder(factor(familiar), mean_aoa))

data_plot <- ggplot(data = p2, aes(x = age_num, y = correct, col = familiar, fill = familiar)) +
  geom_hline(yintercept = 0.5, lty=2)+
  geom_jitter(width = 0, height = 0.05, alpha = .6)+
  geom_smooth(method = "glm", method.args = list(family = "binomial"), se = F, alpha = .5)+
  labs(x="Age",y="Mutual Exclusivity effect")+
  #facet_grid(~familiar)+
  ggtitle("Data")+
  theme_few() +
  ylim(-0.05,1.05)+
  xlim(2,5)+
  guides(alpha = F)+ 
  scale_colour_viridis_d(name = "familiar object")+
  scale_fill_viridis_d(name = "familiar object")
```

```{r plot by numerical age, echo = F}
p4 <- d %>%
  filter(trial != "train1",
         trial != "train2")%>%
    group_by(subage,age_num,subid,subage)%>%
  multi_boot_standard(col = "correct")

ggplot(data = p4, aes(x = age_num, y = mean)) +
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper),size = .8)+
  geom_smooth(method = "lm", se = T, alpha = .5)+
  labs(x="Age",y="Mutual Exclusivity effect")+
  theme_few() +
  ylim(-0.05,1.05)+
  xlim(2,5)+
  guides(alpha = F)+ 
  scale_colour_viridis_d(name = "familiar object")+
  scale_fill_viridis_d(name = "familiar object")
```


```{r}

model <- brm(correct ~ age + (1|subid) + (age | item),
                    data = d, family = bernoulli(),
          control = list(adapt_delta = 0.95),
          sample_prior = F,
          cores = 4, 
          chains = 4,
          save_all_pars = TRUE,
          iter = 2000)

summary(model)

fixef <- as_tibble(fixef(model), rownames = "term")

ranef <-  ranef(model)

ranef_plot <- as_tibble(ranef$item, rownames = "item")%>%
  mutate(grand_intercept = fixef%>%filter(term=="Intercept")%>%pull(Estimate),
         grand_slope = fixef%>%filter(term=="age")%>%pull(Estimate))%>%
  group_by(item) %>%
  expand(Estimate.Intercept,Estimate.age,grand_intercept,grand_slope, age = d$age)%>%
  mutate(y = plogis(grand_intercept + Estimate.Intercept+(Estimate.age+grand_slope)*age), 
         age = age+min(d$age_num))%>%
  left_join(aoa_ratings)%>%
  ungroup()%>%
  mutate(item = fct_reorder(factor(item), mean_aoa))


model_plot <- ggplot(ranef_plot, aes(x=age,y = y, col = item))+
  geom_hline(yintercept = 0.5, lty=2)+
  geom_line(size = 1)+
  ggtitle("Model")+
  labs(x="Age",y="Mutual Exclusivity effect")+
  theme_few() +
  ylim(-0.05,1.05)+
  xlim(2,5)+
  guides(alpha = F)+ 
  scale_colour_viridis_d(name = "familiar object")


```

```{r}
ggarrange(data_plot,model_plot, common.legend = T, legend = "right")
```

```{r}

cor_plot <- as_tibble(ranef$item, rownames = "item") %>%
  left_join(aoa_ratings)

ggplot(cor_plot, aes(x = mean_aoa, y = Estimate.Intercept))+
  geom_point()+
  geom_smooth(method = "lm")+
  xlab("Rated age of acquisition")+
  ylab("ME effect (model intercept)")+
  stat_cor(method = "pearson", label.x = 5, label.y = .99)+
  coord_fixed(ratio = 3)+
  theme_few()
  
```

```{r}
ggsave("../graphs/talk_me_rating_cor.pdf", width = 4, height = 4, scale = 1)
```

```{r}
reduced_model <- brm(correct ~ 1 + (1|subid) + (age_num | familiar),
                    data = d_model, family = bernoulli(),
          control = list(adapt_delta = 0.95),
          sample_prior = F,
          save_all_pars = TRUE,
          iter = 2000)

summary(reduced_model)


child_waic <- brms::WAIC(model, reduced_model, compare = F)

child_weights <- model_weights(model, reduced_model)

# Bayes Factors (slightly variable)
bf_full_null <- bayes_factor(model, reduced_model, log = F, maxiter = 5000)

data_frame(
  model = c("model_w_age","reduced_model"),
  WAIC = c(child_waic$model$estimates[3,1],child_waic$reduced_model$estimates[3,1]),
  SE = c(child_waic$model$estimates[3,2],child_waic$reduced_model$estimates[3,2]),
  weight = c(child_weights[1],child_weights[2]),
  BF10 = c(round(bf_full_null$bf,0),"-"))%>%
  mutate_if(is.numeric, round, 2)
```



