---
title: "Kids Combination"
author: "Manuel Bohn"
output: html_document
---

```{r import data, include = F}
###
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(jsonlite)
library(readxl)
library(brms)

# importing data
files <- dir("~/Work/Spin/raw_data/kids/combination/")

raw_data <- data_frame()
for (f in files) {
  jf <- paste("~/Work/Spin/raw_data/kids/combination/",f,sep="")
  jd <- jsonlite::fromJSON(paste(readLines(jf), collapse=""))
  date <- str_sub(jf,56,str_length(jf)-11)
  id <- as_data_frame(jd$data$data) %>% mutate(test_date = date)
  raw_data <- bind_rows(raw_data, id)
}

d_raw <- raw_data %>%
  mutate(discourseNovel = str_sub(discourseNovel,11),
         mutExNovel = str_sub(mutExNovel, 10),
         subid = ifelse(subid == "190726_6_come", "190726_6_com", subid))

d_raw %>%
  filter(subid == "190727_1_com")


log <- read_excel("../../SPIN-subject_log.xlsx", 1)%>%
  filter(Condition == "com")%>%
  mutate(dob = as.character(dob),
         dob = ifelse(subid == "190620_7_com", "2016-06-20",dob),
         dob = ifelse(subid == "190620_8_com", "2014-10-04",dob),
         dob = ifelse(subid == "190620_14_com", "2016-12-16",dob),
         dob = ifelse(subid == "190711_4_com", "2017-12-11",dob),
         dob = ifelse(subid == "190516_03_com", "2016-05-16",dob),
         dob = ifelse(subid == "190711_4_com", "2016-12-11",dob),
         
         dob = as.Date(dob))%>%
  select(subid,experimenter,keep_drop,sex,dob)


d_raw%>%
  group_by(subid)%>%
  summarise(n())%>%
  filter(!(subid %in% unique(log$subid)))


d <- left_join(d_raw,log, by = "subid")%>%
  filter(keep_drop == "keep")%>%
  mutate(age_num = lubridate::time_length(difftime(test_date,dob), "years"),
         age_num_month = lubridate::time_length(difftime(test_date,dob), "month"),
         age_num_month = round(age_num_month)/12,
         check_age = ifelse(substr(age_num,1,1) == subage, T, F))%>%
    mutate(age = age_num - min(age_num),
           age_month = age_num_month - min(age_num_month))%>%
  filter(condition != "train")%>%
  mutate(alignment = condition,
         item = familiarObject)%>%
  select(-pick_src, -test_date, -experimenter, - keep_drop, -dob, -sex, -check_age, - condition, -familiarObject, -rt)


write_csv(d, "../data/combination.csv")
write_json(d, "../data/combination.json")

 d <- read_csv("../data/combination.csv")%>%
  mutate(subage = factor(subage))

```

```{r}
aoa_ratings_all <- read_xlsx(path = "../data/words_aoa_ratings.xlsx", sheet = 1)

aoa_ratings <- aoa_ratings_all %>%
  filter(Word %in% d$familiarObject )%>%
  mutate(mean_aoa = as.numeric(Rating.Mean),
         familiarObject = Word)%>%
  select(familiarObject,mean_aoa)
```



```{r}
d %>%
  filter(condition != "train")%>%
  group_by(condition,subage) %>%
  summarise(n = length(unique(subid)),
            data_points = n())

#length(unique(d$subid))
```

```{r plot by numerical age, echo = F}
p2 <- d %>%
  filter(condition != "train")%>%
    left_join(aoa_ratings)%>%
  ungroup()%>%
  mutate(familiarObject = fct_reorder(factor(familiarObject), mean_aoa))

ggplot(data = p2, aes(x = age_num, y = correct, col = familiarObject, fill = familiarObject)) +
  geom_hline(yintercept = 0.5, lty=2)+
  geom_jitter(width = 0, height = 0.05, alpha = .6)+
  #geom_smooth(method = "glm", method.args = list(family = "binomial"), se = F, alpha = .5)+
  geom_smooth(method = "loess", se = F, alpha = .5, span = 2)+
  labs(x="Age",y="Mutual Exclusivity effect")+
  #facet_grid(condition~familiarObject)+
  facet_grid(~condition)+
  #ggtitle("Data")+
  theme_few() +
  ylim(-0.05,1.05)+
  xlim(2,5)+
  guides(alpha = F)+ 
  scale_colour_viridis_d(name = "familiar object")+
  scale_fill_viridis_d(name = "familiar object")
```

```{r plot by age, echo= FALSE}
p1 <- d %>%
  filter(condition != "train")%>%
  group_by(subage, familiarObject,condition) %>%
  multi_boot_standard(col = "correct")%>%
  left_join(aoa_ratings)%>%
  ungroup()%>%
  mutate(familiarObject = fct_reorder(factor(familiarObject), mean_aoa))


ggplot(data = p1, aes(x = familiarObject, y = mean, group=1, col = subage)) +
  geom_hline(yintercept = 0.5, lty=2)+
  geom_pointrange(aes(ymin = ci_lower, ymax = ci_upper),size = .8)+
  stat_summary(aes(group = subage, col = subage),fun.y=mean, geom="line")+
  labs(x="",y="Proportion Correct")+
  facet_grid(condition~.)+
  theme_few() +
  ylim(-0.05,1.05)+
  guides(alpha = F)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  scale_colour_solarized()
```



```{r}
d_model <- d %>%
  filter(condition != "train")%>%
  left_join(aoa_ratings)%>%
  mutate(age_num = age_num - mean(age_num),
         aoa = mean_aoa- mean(mean_aoa))

model <- brm(correct ~ familiarObject * age_num * condition + (condition|subid),
                    data = d_model, family = bernoulli(),
          control = list(adapt_delta = 0.99),
          sample_prior = F,
          save_all_pars = TRUE,
          iter = 8000)

summary(model)

```



```{r}
fixef <- as_tibble(readRDS("../saves/fixef_brm_model_item_random_only.rds"), rownames = "term")

ranef <-  readRDS("../saves/ranef_brm_model_item_random_only.rds")

model_plot <- bind_rows(
  as_tibble(ranef$familiar, rownames = "familiar")%>%
  mutate(condition = "congruent",
         condition_code = 0),
  as_tibble(ranef$familiar, rownames = "familiar")%>%
  mutate(condition = "incongruent",
         condition_code = 1))%>%
  mutate(grand_intercept = fixef%>%filter(term=="Intercept")%>%pull(Estimate),
         grand_age = fixef%>%filter(term=="age_num")%>%pull(Estimate),
         grand_cond = fixef%>%filter(term=="conditionincongruent")%>%pull(Estimate),
         grand_intact = fixef%>%filter(term=="age_num:conditionincongruent")%>%pull(Estimate))%>%
  group_by(familiar, condition, condition_code) %>%
  expand(Estimate.Intercept,Estimate.conditionincongruent,Estimate.age_num,`Estimate.age_num:conditionincongruent`,grand_intercept,grand_age,grand_cond,grand_intact,age = d$age_num - mean(d$age_num))%>%
  mutate(y = plogis(grand_intercept + 
                      Estimate.Intercept +
                      grand_cond * condition_code +
                      Estimate.conditionincongruent * condition_code +
                      grand_age * age +
                      Estimate.age_num * age +
                      grand_intact * (condition_code * age) +
                      `Estimate.age_num:conditionincongruent` * (condition_code * age)),
         age = age+mean(d$age_num))%>%
  left_join(aoa_ratings%>%mutate(familiar = familiarObject))%>%
  ungroup()%>%
  mutate(item = fct_reorder(factor(familiar), mean_aoa))


ggplot(model_plot, aes(x=age,y = y, col = familiar))+
  geom_hline(yintercept = 0.5, lty=2)+
  geom_line(size = 1)+
  ggtitle("Model")+
  labs(x="Age",y="Mutual Exclusivity effect")+
  facet_grid(~condition)+
  theme_few() +
  ylim(-0.05,1.05)+
  xlim(2,5)+
  guides(alpha = F)+ 
  scale_colour_viridis_d(name = "familiar object")
```

