---
title: "Familiar words AoA ratings"
author: "Manuel Bohn"
output: html_document
---

```{r import data, include = F}
###
library(tidyverse)
library(knitr)
library(langcog)
library(ggthemes)
library(readxl)
library(ggimage)


## importing data

all_d <- read_xlsx(path = "../data/words_aoa_ratings.xlsx", sheet = 1)

spin_words <- c(
"shoe",
"carrot",
"hat",
"duck",
"bottle",
"cup",
"bread",
"bear",
"truck",
"phone",
"apple",
"horse",
"bowl",
"kite",
"cone",
"tent",
"pencilsharpener",
"horseshoe",
"plug",
"grill",
"garlic",
"antenna",
"violin",
"gear",
"barrel",
"eggplant",
"stethoscope",
"pawn",
"papaya",
"laptop")

d <- all_d %>%
  filter(Word %in% spin_words )%>%
  mutate(Rating.Mean = as.numeric(Rating.Mean))

```


```{r}

spin_select <- c("carrot","duck","bread","apple","kite","horseshoe","plug","garlic","barrel","eggplant","pawn","papaya")

d_select <- d %>%
  mutate(select = if_else(d$Word %in% spin_select, 1.5,-1),
         image = paste("../experiments/kids/images/",Word,".png", sep=""))
```


# Plot by AoA rating
```{r, fig.height=12}

ggplot(d_select, aes(x = reorder(Word, Rating.Mean), y = Rating.Mean)) +
  theme_light(base_size = 22) +
  geom_point(size =5, aes(col = as.character(select)))+
  ylab("Mean Age of Acquisition rating")+
  xlab("Word")+
  guides(col =F)+
  ylim(0,15)+
  theme(axis.text.x = element_text(angle = 60, hjust = 1))+
  geom_linerange(aes(ymin = Rating.Mean+select, ymax = Rating.Mean))+
  geom_image(aes(image=image, y = Rating.Mean+select), asp = 2)+
  scale_color_solarized()

```

```{r}
ggsave("../graphs/talk_items_selection.pdf", width = 12, height = 8, scale = 1.5)
```
