---
title: "Model Samples Processing"
author: "M. Bohn"
date: "18 11 2019"
output: html_document
---

```{r}
library(tidyverse)
#library(rwebppl)
#library(brms)
#library(coda)
#library(ggthemes)
library(readxl)
#library(ggpubr)
library(stringr)
library(matrixStats)
library(data.table)
#library(bigmemory)

estimate_mode <- function(s) {
  d <- density(s)
  return(d$x[which.max(d$y)])
}


hdi_upper<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","upper"])
}

hdi_lower<- function(s){
  m <- HPDinterval(mcmc(s))
  return(m["var1","lower"])
}
```
```{r}

```

# remove chain 6

```{r}
readRDS("../saves/item_params.rds")%>%
  filter(chain != 6)%>%
  saveRDS(., "../saves/item_params.rds")

readRDS("../saves/global_params.rds")%>%
  filter(chain != 6)%>%
  saveRDS(., "../saves/global_params.rds")

readRDS("../saves/item_sigma.rds")%>%
  filter(chain != 6)%>%
  saveRDS(., "../saves/item_sigma.rds")

readRDS("../saves/model_pred_prag.rds")%>%
  filter(chain != 6)%>%
  saveRDS(., "../saves/model_pred_prag.rds")

readRDS("../saves/model_pred_global.rds")%>%
  filter(chain != 6)%>%
  saveRDS(., "../saves/model_pred_global.rds")

readRDS("../saves/model_pred_flat.rds")%>%
  filter(chain != 6)%>%
  saveRDS(., "../saves/model_pred_flat.rds")

readRDS("../saves/model_pred_prior.rds")%>%
  filter(chain != 6)%>%
  saveRDS(., "../saves/model_pred_prior.rds")



```



# Read in raw file

```{r}

model <- bind_rows(
 fread("../webppl/output/samples-fullyBayesian-pragmatic-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain1.csv",header = T)%>%mutate(chain = 1),
 fread("../webppl/output/samples-fullyBayesian-pragmatic-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain2.csv",header = T)%>%mutate(chain = 2),
 fread("../webppl/output/samples-fullyBayesian-pragmatic-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain3.csv",header = T)%>%mutate(chain = 3),
  fread("../webppl/output/samples-fullyBayesian-pragmatic-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain4.csv",header = T)%>%mutate(chain = 4),
  fread("../webppl/output/samples-fullyBayesian-pragmatic-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain5.csv",header = T)%>%mutate(chain = 5),
  fread("../webppl/output/samples-fullyBayesian-pragmatic-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain6.csv",header = T)%>%mutate(chain = 6)
)

# Model Parameters 


item_params <-  model %>%
  filter(b == "items")%>%
  select(-a,-b, -e, -f, -h)%>%
    rename(item = c,
         parameter = d,
         value = g)

saveRDS(item_params, "../saves/item_params_fb.rds")

global_params <- model %>%
  filter(b == "parameters")%>%
  select(-a,-b, -e,-f, -h)%>%
    rename(parameter = c,
         type = d,
         value = g)

saveRDS(global_params, "../saves/global_params_fb.rds")

item_sigma<- model %>%
  filter(b == "sigma",
         c == "global_sem_sigmas")%>%
  select(-a,-b, -e,-f,-h)%>%
    rename(parameter = c,
         type = d,
         value = g)

saveRDS(item_sigma, "../saves/item_sigma_fb.rds")

#subject_sigma<- model %>%
#  filter(b == "sigma", 
#         c != "global_sem_sigmas")%>%
#  select(-a,-b, -e,-f,-h, -d)%>%
#    rename(parameter = c,
#         value = g)

#saveRDS(subject_sigma, "../saves/subject_sigma.rds")

# Model predictions


model_pred_prag <- model %>%
  filter(a == "modelPrediction",
         b == "pragmatic")%>%
  select(-a, -h)%>%
  rename(model = b, 
         parameter = c,
         alignment = d,
         item = e,
         age = f, 
         pred = g)%>%
mutate(model = "fullBayes")

saveRDS(model_pred_prag, "../saves/model_pred_prag_fb.rds")

# model_pred <- model %>%
#   filter(a == "modelPrediction",
#          b == "global")%>%
#   select(-a, -h)%>%
#   rename(model = b, 
#          parameter = c,
#          alignment = d,
#          item = e,
#          age = f, 
#          pred = g)
# 
# saveRDS(model_pred, "../saves/model_pred_global_2.rds")
# 
# model_pred_flat <- model %>%
#   filter(a == "modelPrediction",
#          b == "flat")%>%
#   select(-a, -h)%>%
#   rename(model = b, 
#          parameter = c,
#          alignment = d,
#          item = e,
#          age = f, 
#          pred = g)
# 
# saveRDS(model_pred_flat, "../saves/model_pred_flat_2.rds")
# 
# model_pred_prior <- model %>%
#   filter(a == "modelPrediction",
#          b == "prior")%>%
#   select(-a, -h)%>%
#   rename(model = b, 
#          parameter = c,
#          alignment = d,
#          item = e,
#          age = f, 
#          pred = g)
# 
# saveRDS(model_pred_prior, "../saves/model_pred_prior_2.rds")


```

# combine chains into one file

```{r}
bind_rows(
  readRDS("../saves/item_params_1.rds"),
  readRDS("../saves/item_params_2.rds")
)%>%
  saveRDS(., "../saves/item_params.rds")

bind_rows(
  readRDS("../saves/global_params_1.rds"),
  readRDS("../saves/global_params_2.rds")
)%>%
  saveRDS(., "../saves/global_params.rds")

bind_rows(
  readRDS("../saves/item_sigma_1.rds"),
  readRDS("../saves/item_sigma_2.rds")
)%>%
  saveRDS(., "../saves/item_sigma.rds")


bind_rows(
  readRDS("../saves/model_pred_prag_1.rds"),
  readRDS("../saves/model_pred_prag_2.rds")
)%>%
  saveRDS(., "../saves/model_pred_prag.rds")


bind_rows(
  readRDS("../saves/model_pred_global_1.rds"),
  readRDS("../saves/model_pred_global_2.rds")
)%>%
  saveRDS(., "../saves/model_pred_global.rds")


bind_rows(
  readRDS("../saves/model_pred_flat_1.rds"),
  readRDS("../saves/model_pred_flat_2.rds")
)%>%
  saveRDS(., "../saves/model_pred_flat.rds")


bind_rows(
  readRDS("../saves/model_pred_prior_1.rds"),
  readRDS("../saves/model_pred_prior_2.rds")
)%>%
  saveRDS(., "../saves/model_pred_prior.rds")
```

# mixture model


```{r}

model <- bind_rows(
 fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain1.csv",header = T)%>%mutate(chain = 1),
 fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain2.csv",header = T)%>%mutate(chain = 2),
 fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain3.csv",header = T)%>%mutate(chain = 3),
 fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain4.csv",header = T)%>%mutate(chain = 4),
 fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain5.csv",header = T)%>%mutate(chain = 5),
 fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain6.csv",header = T)%>%mutate(chain = 6),
)

# Model Parameters 


item_params <-  model %>%
  filter(b == "items")%>%
  select(-a,-b, -e, -f, -h)%>%
    rename(item = c,
         parameter = d,
         value = g)

saveRDS(item_params, "../saves/item_params_mm.rds")

global_params <- model %>%
  filter(b == "parameters")%>%
  select(-a,-b, -e,-f, -h)%>%
    rename(parameter = c,
         type = d,
         value = g)

saveRDS(global_params, "../saves/global_params_mm.rds")

item_sigma<- model %>%
  filter(b == "sigma",
         c == "global_sem_sigmas")%>%
  select(-a,-b, -e,-f,-h)%>%
    rename(parameter = c,
         type = d,
         value = g)

saveRDS(item_sigma, "../saves/item_sigma_mm.rds")

mixture<- model %>%
  filter(b == "mixtureComponent")%>%
  select(b,g,chain)%>%
    rename(parameter = b,
         p_informative = g)

saveRDS(mixture, "../saves/mixture_mm.rds")


model_pred_prag <- model %>%
  filter(a == "modelPrediction",
         b == "mixtureModel")%>%
  select(-a, -h, -c)%>%
  rename(model = b, 
         alignment = d,
         item = e,
         age = f, 
         pred = g)

saveRDS(model_pred_prag, "../saves/model_pred_mm.rds")





```

# developmental mixture model


```{r}

model <- bind_rows(
 fread("../webppl/output/samples-fullBayes-devMixtureModel-reFactor-noRandomEffects_mcmc-200_burn100_lag1_chain1.csv",header = T)%>%mutate(chain = 1),
 # fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain2.csv",header = T)%>%mutate(chain = 2),
 # fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain3.csv",header = T)%>%mutate(chain = 3),
 # fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain4.csv",header = T)%>%mutate(chain = 4),
 # fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain5.csv",header = T)%>%mutate(chain = 5),
 # fread("../webppl/output/samples-fullBayes-mixtureModel-reFactor-noRandomEffects_mcmc-100000_burn50000_lag5_chain6.csv",header = T)%>%mutate(chain = 6)
)

# Model Parameters 


item_params <-  model %>%
  filter(b == "items")%>%
  select(-a,-b, -e, -f, -h)%>%
    rename(item = c,
         parameter = d,
         value = g)

saveRDS(item_params, "../saves/item_params_dmm.rds")

global_params <- model %>%
  filter(b == "parameters")%>%
  select(-a,-b, -e,-f, -h)%>%
    rename(parameter = c,
         type = d,
         value = g)

saveRDS(global_params, "../saves/global_params_dmm.rds")

item_sigma<- model %>%
  filter(b == "sigma",
         c == "global_sem_sigmas")%>%
  select(-a,-b, -e,-f,-h)%>%
    rename(parameter = c,
         type = d,
         value = g)

saveRDS(item_sigma, "../saves/item_sigma_dmm.rds")

mixture<- model %>%
  filter(b == "mixtureComponent")%>%
  select(b,c,g,chain)%>%
    rename(parameter = b,
           type = c,
         value = g)

saveRDS(mixture, "../saves/mixture_dmm.rds")


model_pred_prag <- model %>%
  filter(a == "modelPrediction",
         b == "devMixtureModel")%>%
  select(-a, -h, -c)%>%
  rename(model = b, 
         alignment = d,
         item = e,
         age = f, 
         pred = g)

saveRDS(model_pred_prag, "../saves/model_pred_dmm.rds")





```
